### ISSUE TITLE
Credentials.txt or Credentials.text

### ISSUE THREAD

**Issue by schmelto** [aniketsingh98571/HeaLearn#5]
Which file ending is right?

In folder: 

![image](https://user-images.githubusercontent.com/30869493/114394599-ab3bef00-9b9b-11eb-9516-2b43d8cfdb34.png)

In readme:

![image](https://user-images.githubusercontent.com/30869493/114394626-b2fb9380-9b9b-11eb-98ce-d7f3190c7eda.png)

**Comment by aniketsingh98571** [comment]
@schmelto Use the credential from [Credentials.txt](https://github.com/aniketsingh98571/HeaLearn/blob/main/Credentials.text) in order to login into our webapp.

**Comment by schmelto** [comment]
Yeah but should the document renamed to `.txt`? Or is this only the view in my browser?

**Comment by aniketsingh98571** [comment]
Okay, I got it, no there is an issue in file renaming.

**Comment by aniketsingh98571** [comment]
it should be `.txt` only
